project:
  type: book
  output-dir: docs

book:
  title: "IPCC Reports and City Climate Change Plans: Proof of concept prototype - 'Making Climate Readers'"
  author: "FSCI Hackathon Team"
  date: "2023-08-04"
  chapters:
    - q1.qmd
    - q2.qmd
    - q3.qmd
    - q4.qmd
    - q5.qmd
    - index.qmd
    - workflow.qmd
  repo-url: https://github.com/semanticClimate/city-climate-plans-notebook
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: cover.png

comments:
  hypothesis: true

#bibliography: references.bib

format:
  html:
    theme: minty
    number-sections: false
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github
  epub: 
    toc: true   
  
